### PR TITLE
Update package.json version to match microclimate versioning

### PR DESCRIPTION
**Pull request by jonathan-spruce**

### CODE REVIEW

**Comment by tetchel** [comment]
If you run `vsce package` with the version `19.02.0` it will fail because it's not a "semantic version". You'll have to version it `19.2.0`

Interally `vsce` uses [`semver.valid`](https://docs.npmjs.com/misc/semver)

**Comment by jonathan-spruce** [comment]
You're right - I've amended that. I also bumped the version of a couple of license versions in our Theia client extension.

**Comment by jonathan-spruce** [comment]
@tetchel Could you look at this again? If approved I'll merge it and then can get it published on the Visual Studio Marketplace

**Comment by tetchel** [comment]
This PR looks fine but let me suggest some other package.json updates to help publishing:

1. [The doc](https://code.visualstudio.com/api/references/extension-manifest) says only 5 'keywords' are allowed, you have 6. So that might give you trouble.
2. Maybe have the homepage link to our landing pages, perhaps the new profiling info page in particular - The repo is already linked to multiple times from the marketplace site.
3. You can also set a 'bugs' object [like this](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/blob/master/dev/package.json#L11), it shows up as the 'Issues' link on the marketplace

4. The description is probably too long. These guys are short because they show up in the extensions view. The regular Microclimate extension is guilty of this too, though.
image

If you have time, I would also go through the readme and target towards attracting users, rather than towards people who are working on the plugin. You can separate it into two readmes if you want.

**Comment by tetchel** [comment]
Looks great!

**Pull request merged**
